import { EventCategory } from '@fws/core';
import type { NarrativeTemplate } from './types.js';
import { NarrativeTone } from './types.js';

export const characterActionTemplates: NarrativeTemplate[] = [
  // character.befriend
  {
    id: 'character_actions.befriend.low',
    category: EventCategory.Personal,
    subtype: 'character.befriend',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} found common ground with {#if event.data.targetId}{target.name}{#else}a fellow traveler{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.befriend.medium',
    category: EventCategory.Personal,
    subtype: 'character.befriend',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: '{character.name} forged a new friendship with {#if event.data.targetId}{target.name}{#else}a kindred spirit{/if} in the lands of {faction.name}. {#if event.data.motivation}{event.data.motivation}. {/if}What began as chance encounter became a bond of mutual respect.',
    requiredContext: [],
  },
  {
    id: 'character_actions.befriend.high',
    category: EventCategory.Personal,
    subtype: 'character.befriend',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'In the halls of {site.name}, {character.name} and {#if event.data.targetId}{target.name}{#else}an unlikely companion{/if} forged a bond that would echo through the annals of {faction.name}. {#if event.data.relationshipToTarget}Where once stood {event.data.relationshipToTarget}, now blossomed kinship. {/if}{#if event.data.contextDetail}{event.data.contextDetail} {/if}Two souls, once strangers, now stood united against whatever darkness the world might bring.',
    requiredContext: [],
  },

  // character.trade
  {
    id: 'character_actions.trade.low',
    category: EventCategory.Personal,
    subtype: 'character.trade',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} completed a modest exchange{#if event.data.targetId} with {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.trade.medium',
    category: EventCategory.Personal,
    subtype: 'character.trade',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: '{character.name} negotiated a favorable trade{#if event.data.targetId} with {target.name}{/if} at {site.name}. {#if event.data.motivation}{event.data.motivation}. {/if}The exchange brought profit and new connections across the realm.',
    requiredContext: [],
  },
  {
    id: 'character_actions.trade.high',
    category: EventCategory.Personal,
    subtype: 'character.trade',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'The markets of {site.name} bore witness to a deal that would reshape fortunes. {character.name} negotiated with {#if event.data.targetId}{target.name}{#else}a cunning counterpart{/if}, and when the bargain was struck, both parties knew the world had shifted beneath their feet. {#if event.data.contextDetail}{event.data.contextDetail} {/if}Gold changed hands, but so too did the very currents of power.',
    requiredContext: [],
  },

  // character.craft_item
  {
    id: 'character_actions.craft_item.low',
    category: EventCategory.Personal,
    subtype: 'character.craft_item',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} crafted a serviceable item{#if event.data.personalityDriver}, guided by {event.data.personalityDriver}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.craft_item.medium',
    category: EventCategory.Personal,
    subtype: 'character.craft_item',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'In {pronoun.possessive} workshop at {site.name}, {character.name} labored over a new creation. {#if event.data.motivation}{event.data.motivation}. {/if}Skill and patience yielded an item worthy of remark.',
    requiredContext: [],
  },
  {
    id: 'character_actions.craft_item.high',
    category: EventCategory.Personal,
    subtype: 'character.craft_item',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'The forge-fires of {site.name} burned bright as {character.name} wrought a masterwork. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} drove every hammer-strike with unrelenting purpose. {/if}Every detail bore {pronoun.possessive} signature. When at last the work was complete, those who beheld it whispered that such craftsmanship had not been seen since the elder days. {#if event.data.contextDetail}{event.data.contextDetail}{/if}',
    requiredContext: [],
  },

  // character.study_lore
  {
    id: 'character_actions.study_lore.low',
    category: EventCategory.Personal,
    subtype: 'character.study_lore',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} pored over ancient texts{#if event.data.motivation}, driven by {event.data.motivation}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.study_lore.medium',
    category: EventCategory.Personal,
    subtype: 'character.study_lore',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: '{character.name} delved into forgotten lore at {site.name}. {#if event.data.motivation}{event.data.motivation}. {/if}The wisdom of ages past began to reveal itself to {pronoun.object}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.study_lore.high',
    category: EventCategory.Personal,
    subtype: 'character.study_lore',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'Within the archives of {site.name}, {character.name} uncovered knowledge that had slumbered for centuries. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} compelled {pronoun.object} deeper into the stacks than any had ventured before. {/if}Page by page, {pronoun.subject} pieced together truths that the world had forgotten. {#if event.data.contextDetail}{event.data.contextDetail} {/if}The implications would ripple through {faction.name} and beyond, for some knowledge, once awakened, cannot be put to rest.',
    requiredContext: [],
  },

  // character.pray
  {
    id: 'character_actions.pray.low',
    category: EventCategory.Personal,
    subtype: 'character.pray',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} offered prayers to {#if event.data.targetId}{target.name}{#else}the divine{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.pray.medium',
    category: EventCategory.Personal,
    subtype: 'character.pray',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'At {site.name}, {character.name} knelt in supplication{#if event.data.targetId} before {target.name}{/if}. {#if event.data.motivation}{event.data.motivation}. {/if}{pronoun.possessive} devotion burned bright as {pronoun.subject} sought divine favor.',
    requiredContext: [],
  },
  {
    id: 'character_actions.pray.high',
    category: EventCategory.Personal,
    subtype: 'character.pray',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'The sacred halls of {site.name} echoed with {character.name}\'s fervent prayer{#if event.data.targetId} to {target.name}{/if}. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} drove {pronoun.object} to kneel long after others had risen. {/if}Such was {pronoun.possessive} devotion that the very air seemed to shimmer with divine presence. {#if event.data.contextDetail}{event.data.contextDetail} {/if}Whether the gods heard, none could say for certain, but those who witnessed {pronoun.possessive} communion spoke of it for years thereafter.',
    requiredContext: [],
  },

  // character.journey
  {
    id: 'character_actions.journey.low',
    category: EventCategory.Personal,
    subtype: 'character.journey',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} set forth on a journey{#if event.data.motivation}, {event.data.motivation}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.journey.medium',
    category: EventCategory.Personal,
    subtype: 'character.journey',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: '{character.name} departed from {site.name}, seeking new horizons. {#if event.data.motivation}{event.data.motivation}. {/if}The road ahead promised both peril and discovery.',
    requiredContext: [],
  },
  {
    id: 'character_actions.journey.high',
    category: EventCategory.Personal,
    subtype: 'character.journey',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'When {character.name} turned {pronoun.possessive} back upon {site.name}, all who knew {pronoun.object} understood that {pronoun.subject} would return changed, if indeed {pronoun.subject} returned at all. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} would not let {pronoun.object} rest in comfort while the world called. {/if}{#if event.data.contextDetail}{event.data.contextDetail} {/if}The journey ahead would test {pronoun.object} in ways {pronoun.subject} could not yet foresee. Thus began an odyssey that bards would one day sing of.',
    requiredContext: [],
  },

  // character.experiment
  {
    id: 'character_actions.experiment.low',
    category: EventCategory.Personal,
    subtype: 'character.experiment',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} conducted an experiment{#if event.data.personalityDriver}, spurred by {event.data.personalityDriver}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.experiment.medium',
    category: EventCategory.Personal,
    subtype: 'character.experiment',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'In {pronoun.possessive} laboratory at {site.name}, {character.name} pushed the boundaries of known practice. {#if event.data.motivation}{event.data.motivation}. {/if}The results were illuminating.',
    requiredContext: [],
  },
  {
    id: 'character_actions.experiment.high',
    category: EventCategory.Personal,
    subtype: 'character.experiment',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'The chambers beneath {site.name} crackled with arcane energies as {character.name} pursued knowledge that others deemed too dangerous. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} drove {pronoun.object} past every boundary of caution. {/if}When the experiment concluded, the fundamental understanding of {faction.name} had been altered forever. {#if event.data.contextDetail}{event.data.contextDetail} {/if}Some praised {pronoun.possessive} boldness; others whispered that {pronoun.subject} had ventured too far into realms mortals were not meant to tread.',
    requiredContext: [],
  },

  // character.steal
  {
    id: 'character_actions.steal.low',
    category: EventCategory.Personal,
    subtype: 'character.steal',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} pilfered an item{#if event.data.targetId} from {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.steal.medium',
    category: EventCategory.Personal,
    subtype: 'character.steal',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'Under cover of darkness at {site.name}, {character.name} made off with a prize{#if event.data.targetId} belonging to {target.name}{/if}. {#if event.data.motivation}{event.data.motivation}. {/if}The theft would not go unnoticed for long.',
    requiredContext: [],
  },
  {
    id: 'character_actions.steal.high',
    category: EventCategory.Personal,
    subtype: 'character.steal',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'In a daring act that would be spoken of in hushed tones, {character.name} infiltrated the guarded vaults of {site.name} and emerged with a treasure of legendary worth{#if event.data.targetId}, wrested from the grasp of {target.name}{/if}. {#if event.data.relationshipToTarget}The theft was made all the more brazen given they were {event.data.relationshipToTarget}. {/if}{#if event.data.contextDetail}{event.data.contextDetail} {/if}The heist was executed with such cunning that none suspected {pronoun.object} until it was far too late. The reverberations of this theft would shake {faction.name} to its foundations.',
    requiredContext: [],
  },

  // character.proselytize
  {
    id: 'character_actions.proselytize.low',
    category: EventCategory.Personal,
    subtype: 'character.proselytize',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} preached to a small gathering{#if event.data.targetId}, bringing {target.name} into the fold{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.proselytize.medium',
    category: EventCategory.Personal,
    subtype: 'character.proselytize',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: '{character.name} spread the faith through {site.name}{#if event.data.targetId}, swaying even {target.name} with impassioned words{/if}. {#if event.data.motivation}{event.data.motivation}. {/if}The old ways began to give ground to new devotion.',
    requiredContext: [],
  },
  {
    id: 'character_actions.proselytize.high',
    category: EventCategory.Personal,
    subtype: 'character.proselytize',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'Standing before the multitudes of {site.name}, {character.name} proclaimed truth with such fervor that hearts were transformed. {#if event.data.targetId}Even {target.name}, once a skeptic, found {pronoun.reflexive} kneeling. {/if}{#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} lent {pronoun.possessive} words a conviction that could not be denied. {/if}The religious landscape of {faction.name} would never be the same, for {pronoun.subject} had planted seeds that would grow into a movement. {#if event.data.contextDetail}{event.data.contextDetail}{/if}',
    requiredContext: [],
  },

  // character.research_spell
  {
    id: 'character_actions.research_spell.low',
    category: EventCategory.Personal,
    subtype: 'character.research_spell',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} studied the arcane formulae{#if event.data.motivation}, {event.data.motivation}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.research_spell.medium',
    category: EventCategory.Personal,
    subtype: 'character.research_spell',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'Through tireless effort at {site.name}, {character.name} unraveled the mysteries of a potent spell. {#if event.data.motivation}{event.data.motivation}. {/if}Magical theory gave way to practical mastery.',
    requiredContext: [],
  },
  {
    id: 'character_actions.research_spell.high',
    category: EventCategory.Personal,
    subtype: 'character.research_spell',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'The towers of {site.name} hummed with power as {character.name} completed research into magic of unprecedented might. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} fueled nights of ceaseless study that would have broken lesser minds. {/if}What had begun as theoretical musings crystallized into a spell that would reshape the very art of sorcery. {#if event.data.contextDetail}{event.data.contextDetail} {/if}The mage-circles of {faction.name} trembled, for {pronoun.subject} had achieved what many thought impossible.',
    requiredContext: [],
  },

  // character.enchant_item
  {
    id: 'character_actions.enchant_item.low',
    category: EventCategory.Personal,
    subtype: 'character.enchant_item',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} imbued an object with minor enchantment{#if event.data.targetId} for {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.enchant_item.medium',
    category: EventCategory.Personal,
    subtype: 'character.enchant_item',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: '{character.name} wove potent magic into an item at {site.name}. {#if event.data.motivation}{event.data.motivation}. {/if}The enchantment held true, and the result would serve its wielder well.',
    requiredContext: [],
  },
  {
    id: 'character_actions.enchant_item.high',
    category: EventCategory.Personal,
    subtype: 'character.enchant_item',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'In a ritual that lasted three days and three nights, {character.name} bound magic to matter in ways that defied convention. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} sustained {pronoun.object} through the ordeal when lesser enchanters would have faltered. {/if}The item that emerged from {pronoun.possessive} sanctum at {site.name} pulsed with otherworldly power. {#if event.data.contextDetail}{event.data.contextDetail} {/if}Scholars of {faction.name} would study this enchantment for generations, and those who bore it would find their fates irrevocably altered.',
    requiredContext: [],
  },

  // character.forage
  {
    id: 'character_actions.forage.low',
    category: EventCategory.Personal,
    subtype: 'character.forage',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} gathered provisions from the wild{#if event.data.motivation}, {event.data.motivation}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.forage.medium',
    category: EventCategory.Personal,
    subtype: 'character.forage',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'With practiced eye near {site.name}, {character.name} found bounty in the wilderness. {#if event.data.motivation}{event.data.motivation}. {/if}What others overlooked, {pronoun.subject} harvested with skill.',
    requiredContext: [],
  },
  {
    id: 'character_actions.forage.high',
    category: EventCategory.Personal,
    subtype: 'character.forage',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'Venturing deep into untamed lands beyond {site.name}, {character.name} discovered resources thought lost to the ages. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} drove {pronoun.object} farther than any had dared. {/if}{pronoun.possessive} knowledge of nature\'s hidden places yielded a bounty that would sustain {faction.name} through the hard times ahead. {#if event.data.contextDetail}{event.data.contextDetail} {/if}The wilderness had shared its secrets with one who understood its language.',
    requiredContext: [],
  },

  // character.flee
  {
    id: 'character_actions.flee.low',
    category: EventCategory.Personal,
    subtype: 'character.flee',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} withdrew from danger{#if event.data.targetId}, fleeing {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.flee.medium',
    category: EventCategory.Personal,
    subtype: 'character.flee',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'Recognizing that valor would yield only death, {character.name} fled from {site.name}{#if event.data.targetId}, with {target.name} in pursuit{/if}. {#if event.data.motivation}{event.data.motivation}. {/if}Survival demanded retreat.',
    requiredContext: [],
  },
  {
    id: 'character_actions.flee.high',
    category: EventCategory.Personal,
    subtype: 'character.flee',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'When all seemed lost at {site.name}, {character.name} made a desperate escape that few thought possible{#if event.data.targetId}, eluding {target.name} against all odds{/if}. {#if event.data.relationshipToTarget}That {pronoun.subject} fled from {event.data.relationshipToTarget} made the retreat all the more bitter. {/if}Through cunning, luck, and sheer determination, {pronoun.subject} evaded capture when others fell. {#if event.data.contextDetail}{event.data.contextDetail} {/if}The flight would haunt {pronoun.object} for years, yet {pronoun.possessive} survival meant that {faction.name} retained hope for the future.',
    requiredContext: [],
  },

  // character.seek_healing
  {
    id: 'character_actions.seek_healing.low',
    category: EventCategory.Personal,
    subtype: 'character.seek_healing',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} sought treatment{#if event.data.targetId} from {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.seek_healing.medium',
    category: EventCategory.Personal,
    subtype: 'character.seek_healing',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'Wounded and weary, {character.name} came to {site.name} seeking restoration{#if event.data.targetId} at the hands of {target.name}{/if}. {#if event.data.motivation}{event.data.motivation}. {/if}The healers plied their art, and {pronoun.subject} recovered.',
    requiredContext: [],
  },
  {
    id: 'character_actions.seek_healing.high',
    category: EventCategory.Personal,
    subtype: 'character.seek_healing',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'At death\'s very threshold, {character.name} was brought to the sanctuaries of {site.name}. {#if event.data.targetId}{target.name} labored through endless nights, calling upon ancient knowledge and desperate prayers. {#else}The healers labored through endless nights, calling upon ancient knowledge and desperate prayers. {/if}{#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} willed {pronoun.object} to cling to life when the body begged surrender. {/if}Against all expectation, life returned to {pronoun.possessive} broken form. {#if event.data.contextDetail}{event.data.contextDetail} {/if}The recovery would be hailed as miraculous throughout {faction.name}.',
    requiredContext: [],
  },

  // character.dream
  {
    id: 'character_actions.dream.low',
    category: EventCategory.Personal,
    subtype: 'character.dream',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} experienced a vivid dream{#if event.data.targetId} about {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.dream.medium',
    category: EventCategory.Personal,
    subtype: 'character.dream',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'In sleep, {character.name} beheld visions that lingered upon waking{#if event.data.targetId}, visions of {target.name} that felt portentous{/if}. {#if event.data.motivation}{event.data.motivation}. {/if}The dream was laden with meaning.',
    requiredContext: [],
  },
  {
    id: 'character_actions.dream.high',
    category: EventCategory.Personal,
    subtype: 'character.dream',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'A dream of such clarity descended upon {character.name} that {pronoun.subject} could not dismiss it as mere phantasm. {#if event.data.targetId}The figure of {target.name} loomed central among the symbols and portents. {/if}{#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} had opened {pronoun.possessive} mind to truths that waking reason obscured. {/if}When {pronoun.subject} spoke of the dream to the wise of {faction.name}, they grew pale, for such dreams had heralded great changes in ages past. {#if event.data.contextDetail}{event.data.contextDetail}{/if}',
    requiredContext: [],
  },

  // character.betray
  {
    id: 'character_actions.betray.low',
    category: EventCategory.Personal,
    subtype: 'character.betray',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} broke faith with {#if event.data.targetId}{target.name}{#else}an ally{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.betray.medium',
    category: EventCategory.Personal,
    subtype: 'character.betray',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'In an act of calculated treachery, {character.name} turned against {#if event.data.targetId}{target.name}{#else}those who had trusted {pronoun.object}{/if}. {#if event.data.motivation}{event.data.motivation}. {/if}The betrayal would not be forgotten.',
    requiredContext: [],
  },
  {
    id: 'character_actions.betray.high',
    category: EventCategory.Personal,
    subtype: 'character.betray',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'The annals of {faction.name} would record the betrayal of {character.name} as a moment when trust died and cynicism was born. {#if event.data.targetId}{target.name}, who had called {pronoun.object} friend, discovered too late the depths of {pronoun.possessive} duplicity. {#else}Those who had called {pronoun.object} friend discovered too late the depths of {pronoun.possessive} duplicity. {/if}{#if event.data.relationshipToTarget}That they had been {event.data.relationshipToTarget} only deepened the wound. {/if}At {site.name}, the very word "loyalty" took on bitter irony. {#if event.data.contextDetail}{event.data.contextDetail}{/if}',
    requiredContext: [],
  },

  // character.intimidate
  {
    id: 'character_actions.intimidate.low',
    category: EventCategory.Personal,
    subtype: 'character.intimidate',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} used threats to gain {#if event.data.targetId}{target.name}\'s{#else}another\'s{/if} compliance.',
    requiredContext: [],
  },
  {
    id: 'character_actions.intimidate.medium',
    category: EventCategory.Personal,
    subtype: 'character.intimidate',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'With menacing presence at {site.name}, {character.name} bent {#if event.data.targetId}{target.name}{#else}others{/if} to {pronoun.possessive} will. {#if event.data.motivation}{event.data.motivation}. {/if}Fear proved a powerful tool.',
    requiredContext: [],
  },
  {
    id: 'character_actions.intimidate.high',
    category: EventCategory.Personal,
    subtype: 'character.intimidate',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'When {character.name} spoke, {pronoun.possessive} words carried the weight of unspoken violence. {#if event.data.targetId}{target.name} was made to kneel before {pronoun.object}, a lesson for all who watched. {/if}{#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} granted {pronoun.object} an aura that lesser figures could only envy. {/if}Throughout {site.name}, none dared oppose {pronoun.object}, for all had heard what befell those who showed defiance. {#if event.data.contextDetail}{event.data.contextDetail} {/if}{pronoun.possessive} reputation spread through {faction.name} like wildfire, and fear became {pronoun.possessive} most loyal servant.',
    requiredContext: [],
  },

  // character.show_mercy
  {
    id: 'character_actions.show_mercy.low',
    category: EventCategory.Personal,
    subtype: 'character.show_mercy',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} showed mercy to {#if event.data.targetId}{target.name}{#else}a defeated foe{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.show_mercy.medium',
    category: EventCategory.Personal,
    subtype: 'character.show_mercy',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'When justice demanded severity, {character.name} instead offered mercy{#if event.data.targetId} to {target.name}{/if} at {site.name}. {#if event.data.motivation}{event.data.motivation}. {/if}The act surprised many who expected retribution.',
    requiredContext: [],
  },
  {
    id: 'character_actions.show_mercy.high',
    category: EventCategory.Personal,
    subtype: 'character.show_mercy',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'In a moment that would define {pronoun.possessive} legacy, {character.name} stayed {pronoun.possessive} hand when all expected retribution{#if event.data.targetId}, sparing {target.name}{/if}. {#if event.data.relationshipToTarget}That they had been {event.data.relationshipToTarget} made the mercy all the more remarkable. {/if}{#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} overrode the counsel of vengeance. {/if}The mercy shown at {site.name} resonated through {faction.name}, transforming enemies into allies and hatred into gratitude. {#if event.data.contextDetail}{event.data.contextDetail} {/if}Future generations would speak of this compassion as the moment when the cycle of vengeance was finally broken.',
    requiredContext: [],
  },

  // character.negotiate_treaty
  {
    id: 'character_actions.negotiate_treaty.low',
    category: EventCategory.Personal,
    subtype: 'character.negotiate_treaty',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} participated in diplomatic negotiations{#if event.data.targetId} with {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.negotiate_treaty.medium',
    category: EventCategory.Personal,
    subtype: 'character.negotiate_treaty',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: '{character.name} brokered terms of agreement{#if event.data.targetId} with {target.name}{/if} at {site.name}. {#if event.data.motivation}{event.data.motivation}. {/if}Diplomacy proved more effective than the sword.',
    requiredContext: [],
  },
  {
    id: 'character_actions.negotiate_treaty.high',
    category: EventCategory.Personal,
    subtype: 'character.negotiate_treaty',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'The halls of {site.name} witnessed {character.name} navigate treacherous diplomatic waters with masterful skill{#if event.data.targetId}, matching wits with {target.name}{/if}. {#if event.data.relationshipToTarget}That the parties were {event.data.relationshipToTarget} made every concession a delicate gamble. {/if}Each clause was crafted to serve {faction.name} while appearing to compromise. {#if event.data.contextDetail}{event.data.contextDetail} {/if}When the treaty was signed, observers marveled that {pronoun.subject} had achieved what armies could not.',
    requiredContext: [],
  },

  // character.forge_alliance
  {
    id: 'character_actions.forge_alliance.low',
    category: EventCategory.Personal,
    subtype: 'character.forge_alliance',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} formed a political alliance{#if event.data.targetId} with {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.forge_alliance.medium',
    category: EventCategory.Personal,
    subtype: 'character.forge_alliance',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'Through persuasion and shared interests, {character.name} united {#if event.data.targetId}with {target.name}, binding{#else}disparate factions, forging{/if} an alliance that promised mutual benefit. {#if event.data.motivation}{event.data.motivation}.{/if}',
    requiredContext: [],
  },
  {
    id: 'character_actions.forge_alliance.high',
    category: EventCategory.Personal,
    subtype: 'character.forge_alliance',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'Against a backdrop of ancient rivalries and bitter grievances, {character.name} achieved the impossible: an alliance{#if event.data.targetId} with {target.name}{/if} that would reshape the political landscape. {#if event.data.relationshipToTarget}That {event.data.relationshipToTarget} could set aside their differences spoke to the gravity of the moment. {/if}At {site.name}, oaths were sworn that bound {faction.name} to former enemies in common cause. {#if event.data.contextDetail}{event.data.contextDetail} {/if}The architects of this union knew they had witnessed history, for such alliances had toppled empires and birthed new ages.',
    requiredContext: [],
  },

  // character.rally_troops
  {
    id: 'character_actions.rally_troops.low',
    category: EventCategory.Personal,
    subtype: 'character.rally_troops',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} addressed the assembled warriors{#if event.data.motivation}, {event.data.motivation}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.rally_troops.medium',
    category: EventCategory.Personal,
    subtype: 'character.rally_troops',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: '{character.name} stirred the hearts of warriors at {site.name}. {#if event.data.motivation}{event.data.motivation}. {/if}{#if event.data.targetId}{pronoun.subject} spoke of the threat posed by {target.name} and the honor of standing against it. {#else}Morale lifted as {pronoun.subject} spoke of honor and duty. {/if}',
    requiredContext: [],
  },
  {
    id: 'character_actions.rally_troops.high',
    category: EventCategory.Personal,
    subtype: 'character.rally_troops',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'Before the massed ranks of {faction.name}, {character.name} delivered words that would be remembered for generations. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} burned through every syllable, setting fire to the hearts of all who listened. {/if}{pronoun.possessive} voice rang across {site.name}, transforming fear into courage, doubt into certainty. {#if event.data.targetId}Against {target.name}, no sacrifice would be too great, {pronoun.subject} declared. {/if}{#if event.data.contextDetail}{event.data.contextDetail} {/if}The warriors who had marched forth with heavy hearts now burned with renewed purpose, ready to face any foe.',
    requiredContext: [],
  },

  // character.plan_campaign
  {
    id: 'character_actions.plan_campaign.low',
    category: EventCategory.Personal,
    subtype: 'character.plan_campaign',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 0, max: 40 },
    template: '{character.name} devised military strategy{#if event.data.targetId} against {target.name}{/if}.',
    requiredContext: [],
  },
  {
    id: 'character_actions.plan_campaign.medium',
    category: EventCategory.Personal,
    subtype: 'character.plan_campaign',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 41, max: 70 },
    template: 'Poring over maps at {site.name}, {character.name} crafted a campaign{#if event.data.targetId} against {target.name}{/if} of cunning design. {#if event.data.motivation}{event.data.motivation}. {/if}The strategy balanced risk and opportunity.',
    requiredContext: [],
  },
  {
    id: 'character_actions.plan_campaign.high',
    category: EventCategory.Personal,
    subtype: 'character.plan_campaign',
    tone: NarrativeTone.EpicHistorical,
    significanceRange: { min: 71, max: 100 },
    template: 'The war councils of {faction.name} fell silent as {character.name} unveiled a campaign of breathtaking audacity{#if event.data.targetId} directed against {target.name}{/if}. {#if event.data.personalityDriver}{pronoun.possessive} {event.data.personalityDriver} had distilled into a vision of total strategic mastery. {/if}Every contingency had been considered, every advantage exploited, every weakness of the enemy laid bare. {#if event.data.contextDetail}{event.data.contextDetail} {/if}The generals of {site.name} recognized genius when they saw it, and they knew that this campaign would be studied by strategists for centuries to come.',
    requiredContext: [],
  },
];
